services:
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
    ports:
      - "9090:9090" # Only expose Prometheus externally
    depends_on:
      - node-exporter
    networks:
      - monitoring
    restart: unless-stopped

  prometheus-exporter:
    image: prefecthq/prometheus-prefect-exporter:latest
    container_name: prefect-exporter
    # No external ports - only accessible within Docker network
    environment:
      PREFECT_API_URL: http://192.168.0.186:4200/api
      # PREFECT_API_AUTH_STRING: ""
    networks:
      - monitoring
    restart: unless-stopped

  node-exporter:
    image: prom/node-exporter:latest
    container_name: node-exporter
    # No external ports - only accessible within Docker network
    restart: unless-stopped
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - "--path.procfs=/host/proc"
      - "--path.sysfs=/host/sys"
      - "--path.rootfs=/rootfs"
    networks:
      - monitoring

  cadvisor:
    image: gcr.io/cadvisor/cadvisor:latest
    container_name: cadvisor
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    # No external ports - only accessible within Docker network
    restart: unless-stopped
    command:
      - "--docker_only=true"
      - "--disable_metrics=disk,referenced_memory"
    networks:
      - monitoring

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    environment:
      - GF_DASHBOARDS_MIN_REFRESH_INTERVAL=1s
    ports:
      - 3000:3000
    depends_on:
      - prometheus
      - loki
    volumes:
      - ./grafana-data:/var/lib/grafana
    networks:
      - monitoring
      - logging
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 5

  promtail:
    image: grafana/promtail:latest
    container_name: promtrail
    # No external ports - only accessible within Docker network
    volumes:
      - /var/log:/var/log
      #- /var/lib/docker/containers:/var/lib/docker/containers:ro
      - /var/run/docker.sock:/var/run/docker.sock
      - ./promtail-config.yaml:/etc/promtail/promtail.yaml
    command: -config.file=/etc/promtail/promtail.yaml
    networks:
      - logging
    restart: unless-stopped

  loki:
    image: grafana/loki:latest
    container_name: loki
    ports:
      - "3100:3100" # Only expose Loki externally
    command: -config.file=/etc/loki/local-config.yaml
    networks:
      - logging
    restart: unless-stopped

volumes:
  grafana-data:

networks:
  monitoring:
    driver: bridge
    name: prometheus-monitoring
  logging:
    driver: bridge
    name: loki-logging
