services:
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
    ports:
      - "9090:9090"
    depends_on:
      - node-exporter

  prometheus-exporter:
    image: prefecthq/prometheus-prefect-exporter:latest
    ports:
      - "40000:40000"
    environment:
      PREFECT_API_URL: http://localhost:4200/api
      # PREFECT_API_AUTH_STRING: ""

  node-exporter:
    image: prom/node-exporter:latest
    container_name: node-exporter
    #network_mode: "host"
    #pid: "host"
    ports:
      - "9100:9100"
    restart: unless-stopped
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - "--path.procfs=/host/proc"
      - "--path.sysfs=/host/sys"
      - "--path.rootfs=/rootfs"

  cadvisor:
    image: gcr.io/cadvisor/cadvisor:latest
    container_name: cadvisor
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    ports:
      - "8080:8080"
    restart: unless-stopped
    command:
      - "--docker_only=true"
      - "--disable_metrics=disk,referenced_memory"

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    depends_on:
      - prometheus
      - loki
    volumes:
      - ./grafana-data:/var/lib/grafana

  promtail:
    image: grafana/promtail:latest
    container_name: promtrail
    ports:
      - "9080:9080"
    volumes:
      - /var/log:/var/log
      #- /etc/promtail:/etc/promtail
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - ./promtail-config.yaml:/etc/promtail/promtail.yaml
    command: -config.file=/etc/promtail/promtail.yaml

  loki:
    image: grafana/loki:latest
    container_name: loki
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml

volumes:
  grafana-data:
