server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: system
    static_configs:
      - targets:
          - localhost
        labels:
          job: varlogs
          __path__: /var/log/*.log

  #- job_name: docker
  #  static_configs:
  #    - targets:
  #        - localhost
  #      labels:
  #        job: docker
  #        __path__: /var/lib/docker/containers/*/*.log

  - job_name: docker-dev
    docker_sd_configs:
      - host: unix:///var/run/docker.sock
        refresh_interval: 2s
        #filters:
        #  - name: name
        #    values: [prefect*]
    relabel_configs:
      - target_label: 'job'
        replacement: 'docker-dev'
      - source_labels: ['__meta_docker_container_name']
        regex: '/(.*)'
        target_label: 'container'
      - source_labels: ['__meta_docker_container_log_stream']
        target_label: 'stream'
      - source_labels: ['__meta_docker_container_label_com_docker_compose_project']
        target_label: 'stack'
