global:
  scrape_interval: 15s

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: "node-exporter"
    static_configs:
      - targets: ["node-exporter:9100"]

  - job_name: "cadvisor"
    static_configs:
      - targets: ["cadvisor:8080"]

  - job_name: "prefect"
    static_configs:
      - targets: ["prefect-exporter:40000"]

  - job_name: "prod-node"
    static_configs:
      - targets: ["192.168.0.186:19100"]

  - job_name: "prod-cadvisor"
    static_configs:
      - targets: ["192.168.0.186:18080"]
