server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://localhost:3100/loki/api/v1/push # <-- Use your dev server's IP

scrape_configs:
  - job_name: varlogs-prod
    static_configs:
      - targets: [localhost]
        labels:
          job: varlogs-prod
          __path__: /var/log/*.log

  #- job_name: docker-prod
  #  static_configs:
  #    - targets: [localhost]
  #      labels:
  #        job: docker-prod
  #        __path__: /var/lib/docker/containers/*/*.logc

  - job_name: docker-prod
    docker_sd_configs:
      - host: unix:///var/run/docker.sock
        refresh_interval: 10s
        filters:
          - name: label
            values: ["logger=loki"]
    relabel_configs:
      - target_label: 'job'
        replacement: 'docker'
      - source_labels: ['__meta_docker_container_name']
        regex: '/(.*)'
        target_label: 'container'
      - source_labels: ['__meta_docker_container_log_stream']
        target_label: 'stream'
