server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://localhost:3100/loki/api/v1/push # <-- Use your dev server's IP

scrape_configs:
  - job_name: varlogs-prod
    static_configs:
      - targets: [localhost]
        labels:
          job: varlogs-prod
          __path__: /var/log/*.log

  - job_name: docker-prod
    static_configs:
      - targets: [localhost]
        labels:
          job: docker-prod
          __path__: /var/lib/docker/containers/*/*.logc
